arch:
    - amd64
    - ppc64le
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y figlet cowsay
sudo: required
language: go
go: 1.11.x
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- PATH="$HOME/gopath/bin:$PATH"
- script/coverage --coveralls
after_success:
- figlet "Build Successful!" | /usr/games/cowsay -n -e "^^"
after_failure:
- figlet "Build Failed!" | /usr/games/cowsay -n -s
